from typing import Optional, Tuple

from scapy.fields import ByteField, LEShortField
from scapy.packet import Packet

from ..fields import (
    ArtemisSBSByteBooleanField,
)
from ._properties import gen_fields


class PlayerShipUpgradesProperties(Packet):
    name = "Player Ship Upgrades Properties "
    fields_desc = gen_fields(
        [
            ArtemisSBSByteBooleanField("active_infusion_p_coils", None),
            ArtemisSBSByteBooleanField("active_hydrogen_ram", None),
            ArtemisSBSByteBooleanField("active_tauron_focusers", None),
            ArtemisSBSByteBooleanField("active_carapaction_coils", None),
            ArtemisSBSByteBooleanField("active_polyphasic_capacitors", None),
            ArtemisSBSByteBooleanField("active_cetrocite_crystals", None),
            ArtemisSBSByteBooleanField("active_lateral_array", None),
            ArtemisSBSByteBooleanField("active_ecm_starpulse", None),
            ArtemisSBSByteBooleanField("active_double_agent", None),
            ArtemisSBSByteBooleanField("active_wartime_production", None),
            ArtemisSBSByteBooleanField("active_infusion_p_coils_perm", None),
            ArtemisSBSByteBooleanField("active_protonic_verniers", None),
            ArtemisSBSByteBooleanField("active_tauron_focusers_perm", None),
            ArtemisSBSByteBooleanField("active_regenerative_pau_grids", None),
            ArtemisSBSByteBooleanField("active_veteran_damcon_teams", None),
            ArtemisSBSByteBooleanField("active_cetrocite_heatsinks", None),
            ArtemisSBSByteBooleanField("active_tachyon_scanners", None),
            ArtemisSBSByteBooleanField("active_gridscan_overload", None),
            ArtemisSBSByteBooleanField("active_override_authorization", None),
            ArtemisSBSByteBooleanField("active_resupply_imperatives", None),
            ArtemisSBSByteBooleanField("active_patrol_group", None),
            ArtemisSBSByteBooleanField("active_fast_supply", None),
            ArtemisSBSByteBooleanField("active_vanguard_refit_helm", None),
            ArtemisSBSByteBooleanField("active_vanguard_refit_weap", None),
            ArtemisSBSByteBooleanField("active_vanguard_refit_comm", None),
            ArtemisSBSByteBooleanField("active_vanguard_refit_station", None),
            ArtemisSBSByteBooleanField("active_vanguard_refit_eng", None),
            ArtemisSBSByteBooleanField("active_vanguard_refit_systems", None),
            ByteField("count_infusion_p_coils", None),
            ByteField("count_hydrogen_ram", None),
            ByteField("count_tauron_focusers", None),
            ByteField("count_carapaction_coils", None),
            ByteField("count_polyphasic_capacitors", None),
            ByteField("count_cetrocite_crystals", None),
            ByteField("count_lateral_array", None),
            ByteField("count_ecm_starpulse", None),
            ByteField("count_double_agent", None),
            ByteField("count_wartime_production", None),
            ByteField("count_infusion_p_coils_perm", None),
            ByteField("count_protonic_verniers", None),
            ByteField("count_tauron_focusers_perm", None),
            ByteField("count_regenerative_pau_grids", None),
            ByteField("count_veteran_damcon_teams", None),
            ByteField("count_cetrocite_heatsinks", None),
            ByteField("count_tachyon_scanners", None),
            ByteField("count_gridscan_overload", None),
            ByteField("count_override_authorization", None),
            ByteField("count_resupply_imperatives", None),
            ByteField("count_patrol_group", None),
            ByteField("count_fast_supply", None),
            ByteField("count_vanguard_refit_helm", None),
            ByteField("count_vanguard_refit_weap", None),
            ByteField("count_vanguard_refit_comm", None),
            ByteField("count_vanguard_refit_station", None),
            ByteField("count_vanguard_refit_eng", None),
            ByteField("count_vanguard_refit_systems", None),
            LEShortField("time_infusion_p_coils", None),
            LEShortField("time_hydrogen_ram", None),
            LEShortField("time_tauron_focusers", None),
            LEShortField("time_carapaction_coils", None),
            LEShortField("time_polyphasic_capacitors", None),
            LEShortField("time_cetrocite_crystals", None),
            LEShortField("time_lateral_array", None),
            LEShortField("time_ecm_starpulse", None),
            LEShortField("time_double_agent", None),
            LEShortField("time_wartime_production", None),
            LEShortField("time_infusion_p_coils_perm", None),
            LEShortField("time_protonic_verniers", None),
            LEShortField("time_tauron_focusers_perm", None),
            LEShortField("time_regenerative_pau_grids", None),
            LEShortField("time_veteran_damcon_teams", None),
            LEShortField("time_cetrocite_heatsinks", None),
            LEShortField("time_tachyon_scanners", None),
            LEShortField("time_gridscan_overload", None),
            LEShortField("time_override_authorization", None),
            LEShortField("time_resupply_imperatives", None),
            LEShortField("time_patrol_group", None),
            LEShortField("time_fast_supply", None),
            LEShortField("time_vanguard_refit_helm", None),
            LEShortField("time_vanguard_refit_weap", None),
            LEShortField("time_vanguard_refit_comm", None),
            LEShortField("time_vanguard_refit_station", None),
            LEShortField("time_vanguard_refit_eng", None),
            LEShortField("time_vanguard_refit_systems", None),
        ]
    )

    def extract_padding(self, s: bytes) -> Tuple[bytes, Optional[bytes]]:
        return b"", s
